// <auto-generated />
using System;
using MicroCashDevWPFUI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroCashDevWPFUI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120020451_UpdateProdukBatchTanggalKadaluarsaNullable")]
    partial class UpdateProdukBatchTanggalKadaluarsaNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaBank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomorRekening")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.DetailPembelian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HargaBeli")
                        .HasColumnType("TEXT");

                    b.Property<int>("Jumlah")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PembelianId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdukSatuanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PembelianId");

                    b.HasIndex("ProdukSatuanId");

                    b.ToTable("DetailPembelians");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.DetailPenjualan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Harga")
                        .HasColumnType("TEXT");

                    b.Property<int>("Jumlah")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PenjualanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdukSatuanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PenjualanId");

                    b.HasIndex("ProdukSatuanId");

                    b.ToTable("DetailPenjualans");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaMenu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PageKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Urutan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PembelianId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusPembayaran")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalDeadline")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("PembelianId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Pembelian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomorFaktur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Pembelians");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Penjualan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Dibayar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kembalian")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomorNota")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Penjualans");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaBarang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produks");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.ProdukBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DetailPembelianId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdukSatuanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TanggalKadarluasa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalMasuk")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetailPembelianId");

                    b.HasIndex("ProdukSatuanId");

                    b.ToTable("ProdukBatchs");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.ProdukSatuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HargaJual")
                        .HasColumnType("TEXT");

                    b.Property<int>("JumlahPerSatuan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdukId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SatuanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdukId");

                    b.HasIndex("SatuanId");

                    b.ToTable("ProdukSatuans");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.ProfileToko", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KataSambutan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaToko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProfileTokos");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Satuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaSatuan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Satuans");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaSupplier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.UserMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMenus");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Bank", b =>
                {
                    b.HasOne("MicroCashDevWPFUI.Models.Supplier", "Supplier")
                        .WithMany("Banks")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.DetailPembelian", b =>
                {
                    b.HasOne("MicroCashDevWPFUI.Models.Pembelian", "Pembelian")
                        .WithMany("DetailPembelians")
                        .HasForeignKey("PembelianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroCashDevWPFUI.Models.ProdukSatuan", "ProdukSatuan")
                        .WithMany("DetailPembelians")
                        .HasForeignKey("ProdukSatuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pembelian");

                    b.Navigation("ProdukSatuan");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.DetailPenjualan", b =>
                {
                    b.HasOne("MicroCashDevWPFUI.Models.Penjualan", "Penjualan")
                        .WithMany("DetailPenjualans")
                        .HasForeignKey("PenjualanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroCashDevWPFUI.Models.ProdukSatuan", "ProdukSatuan")
                        .WithMany("DetailPenjualans")
                        .HasForeignKey("ProdukSatuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Penjualan");

                    b.Navigation("ProdukSatuan");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Menu", b =>
                {
                    b.HasOne("MicroCashDevWPFUI.Models.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Nota", b =>
                {
                    b.HasOne("MicroCashDevWPFUI.Models.Bank", "Bank")
                        .WithMany("Notas")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroCashDevWPFUI.Models.Pembelian", "Pembelian")
                        .WithMany("Notas")
                        .HasForeignKey("PembelianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Pembelian");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Pembelian", b =>
                {
                    b.HasOne("MicroCashDevWPFUI.Models.Supplier", "Supplier")
                        .WithMany("Pembelians")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Penjualan", b =>
                {
                    b.HasOne("MicroCashDevWPFUI.Models.User", "User")
                        .WithMany("Penjualans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.ProdukBatch", b =>
                {
                    b.HasOne("MicroCashDevWPFUI.Models.DetailPembelian", "DetailPembelian")
                        .WithMany("ProdukBatchs")
                        .HasForeignKey("DetailPembelianId");

                    b.HasOne("MicroCashDevWPFUI.Models.ProdukSatuan", "ProdukSatuan")
                        .WithMany("ProdukBatchs")
                        .HasForeignKey("ProdukSatuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailPembelian");

                    b.Navigation("ProdukSatuan");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.ProdukSatuan", b =>
                {
                    b.HasOne("MicroCashDevWPFUI.Models.Produk", "Produk")
                        .WithMany("ProdukSatuans")
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroCashDevWPFUI.Models.Satuan", "Satuan")
                        .WithMany("ProdukSatuans")
                        .HasForeignKey("SatuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produk");

                    b.Navigation("Satuan");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.UserMenu", b =>
                {
                    b.HasOne("MicroCashDevWPFUI.Models.Menu", "Menu")
                        .WithMany("UserMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroCashDevWPFUI.Models.User", "User")
                        .WithMany("UserMenus")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Bank", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.DetailPembelian", b =>
                {
                    b.Navigation("ProdukBatchs");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("UserMenus");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Pembelian", b =>
                {
                    b.Navigation("DetailPembelians");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Penjualan", b =>
                {
                    b.Navigation("DetailPenjualans");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Produk", b =>
                {
                    b.Navigation("ProdukSatuans");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.ProdukSatuan", b =>
                {
                    b.Navigation("DetailPembelians");

                    b.Navigation("DetailPenjualans");

                    b.Navigation("ProdukBatchs");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Satuan", b =>
                {
                    b.Navigation("ProdukSatuans");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.Supplier", b =>
                {
                    b.Navigation("Banks");

                    b.Navigation("Pembelians");
                });

            modelBuilder.Entity("MicroCashDevWPFUI.Models.User", b =>
                {
                    b.Navigation("Penjualans");

                    b.Navigation("UserMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
