<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>MicroCashDevWPFUI.App</StartupObject>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyTitle>MicroCash</AssemblyTitle>
    <AssemblyName>MicroCash</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
    <Content Include="wpfui-icon.ico" />
  </ItemGroup>

    <ItemGroup>
    <PackageReference Include="Autofac" Version="9.0.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260222" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260222" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="ScottPlot.WPF" Version="5.1.57" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.3" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="WPF-UI" Version="4.1.0" />
    <PackageReference Include="WPF-UI.DependencyInjection" Version="4.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0 " />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\logo.png" />
    <None Remove="Assets\wpfui-icon-256.png" />
    <None Remove="Assets\wpfui-icon-1024.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.png">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\wpfui-icon-256.png" />
    <Resource Include="Assets\wpfui-icon-1024.png" />
  </ItemGroup>

  <ItemGroup>
     <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
